import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Mohamed',
      email: 'alloulialloulimohamed2023@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Adnane',
      email: 'adnaneelmoustaghfir240101@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
  ],
  products: [
    {
      //_id: '1',
      name: 'iPhone 13 Pro',
      slug: 'iphone-13-pro',
      category: 'Smartphones',
      image: '/images/p1.jpg', // Example image dimensions
      price: 999,
      countInStock: 15,
      brand: 'Apple',
      rating: 4.8,
      numReviews: 120,
      description: 'Apple iPhone 13 Pro with A15 Bionic chip and advanced camera system.',
    },
    {
      //_id: '2',
      name: 'Samsung Galaxy S21 Ultra',
      slug: 'samsung-galaxy-s21-ultra',
      category: 'Smartphones',
      image: '/images/p2.jpg', // Example image dimensions
      price: 1199,
      countInStock: 8,
      brand: 'Samsung',
      rating: 4.7,
      numReviews: 95,
      description: 'Samsung Galaxy S21 Ultra with 108MP camera and powerful Exynos 2100 chipset.',
    },
    {
      //_id: '3',
      name: 'Google Pixel 6',
      slug: 'google-pixel-6',
      category: 'Smartphones',
      image: '/images/p3.jpg', // Example image dimensions
      price: 699,
      countInStock: 20,
      brand: 'Google',
      rating: 4.6,
      numReviews: 80,
      description: 'Google Pixel 6 with Tensor chip and intelligent camera features.',
    },
    {
      //_id: '4',
      name: 'OnePlus 9 Pro',
      slug: 'oneplus-9-pro',
      category: 'Smartphones',
      image: '/images/p4.jpg', // Example image dimensions
      price: 899,
      countInStock: 12,
      brand: 'OnePlus',
      rating: 4.5,
      numReviews: 60,
      description: 'OnePlus 9 Pro with Hasselblad camera system and Snapdragon 888 chipset.',
    },
    {
      //_id: '5',
      name: 'Sony Xperia 1 III',
      slug: 'sony-xperia-1-iii',
      category: 'Smartphones',
      image: '/images/p5.jpg', // Example image dimensions
      price: 1199,
      countInStock: 5,
      brand: 'Sony',
      rating: 4.4,
      numReviews: 45,
      description: 'Sony Xperia 1 III with 4K OLED display and triple-lens camera system.',
    },
    {
      //_id: '6',
      name: 'Xiaomi Mi 11',
      slug: 'xiaomi-mi-11',
      category: 'Smartphones',
      image: '/images/p6.jpg', // Example image dimensions
      price: 749,
      countInStock: 25,
      brand: 'Xiaomi',
      rating: 4.6,
      numReviews: 70,
      description: 'Xiaomi Mi 11 with Snapdragon 888 and 108MP camera.',
    },
    {
     // _id: '1',
      name: 'Canon EOS R5',
      slug: 'canon-eos-r5',
      category: 'Cameras',
      image: '/images/p7.jpg', // Example image dimensions
      price: 3899,
      countInStock: 12,
      brand: 'Canon',
      rating: 4.9,
      numReviews: 85,
      description: 'Canon EOS R5 with 45MP full-frame sensor and 8K video recording.',
    },
    {
     // _id: '2',
      name: 'Nikon Z7 II',
      slug: 'nikon-z7-ii',
      category: 'Cameras',
      image: '/images/p8.jpg', // Example image dimensions
      price: 2999,
      countInStock: 15,
      brand: 'Nikon',
      rating: 4.7,
      numReviews: 70,
      description: 'Nikon Z7 II with 45.7MP full-frame sensor and dual processors for fast performance.',
    },
    {
      //_id: '3',
      name: 'Sony Alpha 1',
      slug: 'sony-alpha-1',
      category: 'Cameras',
      image: '/images/p9.jpg', // Example image dimensions
      price: 6499,
      countInStock: 5,
      brand: 'Sony',
      rating: 4.9,
      numReviews: 50,
      description: 'Sony Alpha 1 with 50MP sensor and 8K 30p video recording capabilities.',
    },
    {
     // _id: '4',
      name: 'Fujifilm X-T4',
      slug: 'fujifilm-x-t4',
      category: 'Cameras',
      image: '/images/p10.jpg', // Example image dimensions
      price: 1699,
      countInStock: 18,
      brand: 'Fujifilm',
      rating: 4.8,
      numReviews: 120,
      description: 'Fujifilm X-T4 mirrorless camera with 26.1MP sensor and in-body stabilization.',
    },
    {
      //_id: '5',
      name: 'Panasonic Lumix GH5 II',
      slug: 'panasonic-lumix-gh5-ii',
      category: 'Cameras',
      image: '/images/p11.jpg', // Example image dimensions
      price: 1499,
      countInStock: 10,
      brand: 'Panasonic',
      rating: 4.6,
      numReviews: 65,
      description: 'Panasonic Lumix GH5 II with 20.3MP sensor and professional 4K video recording.',
    },
    {
      //_id: '6',
      name: 'Leica Q2',
      slug: 'leica-q2',
      category: 'Cameras',
      image: '/images/p12.jpg', // Example image dimensions
      price: 5499,
      countInStock: 7,
      brand: 'Leica',
      rating: 4.7,
      numReviews: 30,
      description: 'Leica Q2 with 47.3MP full-frame sensor and fixed 28mm lens.',
    },
  ],
};
export default data;
